# 实验名称
experiment: "CAN"

# 随机种子
seed: 20211024

# 训练参数
epochs: 240
batch_size: 8
workers: 0
train_parts: 1
valid_parts: 1
valid_start: 0
save_start: 0

# 优化器设置
optimizer: AdamW
lr: 1e-3            # AdamW通常使用较小的初始学习率，如1e-3或1e-4
lr_decay: cosine
eps: 1e-8           # AdamW的默认eps通常为1e-8
weight_decay: 1e-4
beta1: 0.9          # 默认β1值
beta2: 0.999        # 默认β2值

dropout: True
dropout_ratio: 0.5
relu: True
gradient: 100
gradient_clip: True
use_label_mask: False

# 训练数据
# train_image_path: 'datasets/CROHME/train_images.pkl'
train_image_path: 'E:\Project_storage\others\OS_and_Study_Markdown\神经网络课程设计\project_2024_LaTeX_OCR_Pytorch-master\data\MyDataset'
train_label_path: 'datasets/CROHME/train_labels.txt'

# eval_image_path: 'datasets/CROHME/14_test_images.pkl'
eval_image_path: 'E:\Project_storage\others\OS_and_Study_Markdown\神经网络课程设计\project_2024_LaTeX_OCR_Pytorch-master\data\MyDataset\test_dataset'
eval_label_path: 'datasets/CROHME/14_test_labels.txt'

word_path: 'datasets/CROHME/words_dict.txt'
word_num: 415

# collate_fn
collate_fn: collate_fn

densenet:
  ratio: 16
  growthRate: 24
  reduction: 0.5
  bottleneck: True
  use_dropout: True

encoder:
  input_channel: 3
  out_channel: 684

decoder:
  net: AttDecoder
  cell: 'GRU'
  input_size: 256
  hidden_size: 256

counting_decoder:
  in_channel: 684
  out_channel: 415

attention:
  attention_dim: 512
  word_conv_kernel: 1

attention_map_vis_path: 'vis/attention_map'
counting_map_vis_path: 'vis/counting_map'

whiten_type: None
max_step: 256

optimizer_save: False
finetune: False
checkpoint_dir: 'checkpoints'
checkpoint: ""
log_dir: 'logs'

